# Generated by Django 5.2.3 on 2025-08-04 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('certificacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'certificacion',
            },
        ),
        migrations.CreateModel(
            name='FechaDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('rubro_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'rubro',
            },
        ),
        migrations.CreateModel(
            name='TipoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('tipo_doc', models.CharField(max_length=20)),
                ('num_doc', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('rol', models.CharField(blank=True, max_length=20)),
                ('fecha_registro', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='EmpresaCertificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.certificacion')),
            ],
            options={
                'db_table': 'empresaexportadora_certificaciones',
            },
        ),
        migrations.CreateModel(
            name='EmpresaExportadora',
            fields=[
                ('empresa_id', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('brochure', models.FileField(upload_to='brochures/')),
                ('logo', models.ImageField(upload_to='logos/')),
                ('capacidad_productiva', models.IntegerField(db_column='capacidad_mensual')),
                ('exporta_actualmente', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=2)),
                ('frecuencia_exportacion', models.CharField(choices=[('Ocasional', 'Ocasional'), ('Frecuente', 'Frecuente'), ('Regular', 'Regular')], max_length=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('certificaciones', models.ManyToManyField(through='gestion.EmpresaCertificacion', to='gestion.certificacion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.localidad')),
            ],
            options={
                'db_table': 'empresaexportadora',
            },
        ),
        migrations.AddField(
            model_name='empresacertificacion',
            name='empresa',
            field=models.ForeignKey(db_column='empresa_id', on_delete=django.db.models.deletion.CASCADE, to='gestion.empresaexportadora'),
        ),
        migrations.CreateModel(
            name='EmpresaPais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(db_column='empresa_id', on_delete=django.db.models.deletion.CASCADE, to='gestion.empresaexportadora')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.pais')),
            ],
            options={
                'db_table': 'empresaexportadora_paises_exporta',
                'unique_together': {('empresa', 'pais')},
            },
        ),
        migrations.AddField(
            model_name='empresaexportadora',
            name='paises_exporta',
            field=models.ManyToManyField(blank=True, through='gestion.EmpresaPais', to='gestion.pais'),
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.pais')),
            ],
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.provincia'),
        ),
        migrations.CreateModel(
            name='Importador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=30)),
                ('empleados', models.IntegerField()),
                ('sitio_web', models.URLField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_importador/')),
                ('tipo_importador', models.CharField(choices=[('Distribuidor mayorista', 'Distribuidor mayorista'), ('Distribuidor minorista', 'Distribuidor minorista'), ('Retailer / Cadena comercial', 'Retailer / Cadena comercial'), ('Otro', 'Otro')], max_length=50)),
                ('tipo_importador_otro', models.CharField(blank=True, max_length=100, null=True)),
                ('experiencia_proveedores_arg', models.BooleanField()),
                ('presentacion_buscada', models.CharField(choices=[('A granel', 'A granel'), ('Fraccionado', 'Fraccionado'), ('Ambos', 'Ambos'), ('No aplica', 'No aplica')], max_length=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('idiomas', models.ManyToManyField(to='gestion.idioma')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.localidad')),
                ('pais_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.pais')),
                ('paises_comercializa', models.ManyToManyField(related_name='importadores_que_comercializan', to='gestion.pais')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.provincia')),
                ('rubros', models.ManyToManyField(to='gestion.rubro')),
                ('tipos_proveedor', models.ManyToManyField(to='gestion.tipoproveedor')),
            ],
        ),
        migrations.AddField(
            model_name='empresaexportadora',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.provincia'),
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('hora', models.TimeField()),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='Programada', max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.empresaexportadora')),
                ('importador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.importador')),
            ],
        ),
        migrations.AddField(
            model_name='empresaexportadora',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.rubro'),
        ),
        migrations.AlterUniqueTogether(
            name='empresacertificacion',
            unique_together={('empresa', 'certificacion')},
        ),
    ]
