# Generated by Django 5.2.3 on 2025-08-04 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='reunion',
            name='horario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.horariodisponible'),
        ),
        migrations.AlterUniqueTogether(
            name='reunion',
            unique_together={('fecha', 'horario')},
        ),
        migrations.RemoveField(
            model_name='reunion',
            name='hora',
        ),
    ]
