# Generated by Django 5.2.3 on 2025-08-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_horariodisponible_reunion_horario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permitir_registro', models.BooleanField(default=True)),
                ('permitir_login', models.BooleanField(default=True)),
            ],
        ),
    ]
