# Generated by Django 5.2.3 on 2025-08-27 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_configuracionsistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrefijoTelefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True, verbose_name='Codigo')),
                ('pais', models.CharField(max_length=50, verbose_name='Pais')),
            ],
        ),
        migrations.AlterField(
            model_name='empresaexportadora',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Numero de Telefono'),
        ),
        migrations.AlterField(
            model_name='importador',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Numero de Telefono'),
        ),
        migrations.AddField(
            model_name='empresaexportadora',
            name='prefijo_telefono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.prefijotelefono'),
        ),
        migrations.AddField(
            model_name='importador',
            name='prefijo_telefono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.prefijotelefono'),
        ),
    ]
