# Generated by Django 5.2.3 on 2025-08-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_prefijotelefono_alter_empresaexportadora_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importador',
            name='empleados',
            field=models.CharField(choices=[('1-10', '1 a 10'), ('11-50', '11 a 50'), ('51-200', '51 a 200'), ('200+', 'Más de 200')], max_length=10),
        ),
    ]
