# Generated by Django 5.2.3 on 2025-08-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_importador_empleados'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechadisponible',
            name='habilitada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='fecha',
            field=models.DateField(),
        ),
    ]
