# Generated by Django 5.2.3 on 2025-09-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_fechadisponible_habilitada_alter_reunion_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresaexportadora',
            name='frecuencia_exportacion',
        ),
    ]
