# Generated by Django 5.2.3 on 2025-09-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_unidadmedida_empresaexportadora_unidad_capacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresaexportadora',
            name='logo',
            field=models.ImageField(blank=True, default='media/logos/default_logo.jpg', null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='importador',
            name='logo',
            field=models.ImageField(blank=True, default='media/logos/default_logo.jpg', null=True, upload_to='logos/'),
        ),
    ]
