# Generated by Django 5.2.3 on 2025-09-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_empresaexportadora_logo_alter_importador_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresaexportadora',
            name='logo',
            field=models.ImageField(blank=True, default='logos/default_logo.jpg', null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='importador',
            name='logo',
            field=models.ImageField(blank=True, default='logos/default_logo.jpg', null=True, upload_to='logos/'),
        ),
    ]
