# Generated by Django 5.2.3 on 2025-09-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_empresaexportadora_logo_alter_importador_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importador',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
