# Generated by Django 5.2.3 on 2025-09-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_importador_sitio_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importador',
            name='tipo_importador_otro',
        ),
        migrations.AlterField(
            model_name='importador',
            name='tipo_importador',
            field=models.CharField(choices=[('distribuidor_mayorista', 'Distribuidor Mayorista'), ('distribuidor_minorista', 'Distribuidor Minorista'), ('retail', 'Retailer / Cadena comercial'), ('otro', 'Otro')], max_length=50),
        ),
    ]
