# Generated by Django 5.2.3 on 2025-09-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_remove_importador_tipo_importador_otro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importador',
            name='tipo_importador',
            field=models.CharField(choices=[('distribuidor_mayorista', 'Distribuidor Mayorista'), ('distribuidor_minorista', 'Distribuidor Minorista'), ('retail', 'Retailer / Cadena comercial'), ('e_comerce', 'E-commerce'), ('broker', 'Broker / Agente comercial'), ('otro', 'Otro')], max_length=50),
        ),
    ]
