# Generated by Django 5.2.3 on 2025-09-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_alter_importador_tipo_importador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importador',
            name='idiomas',
            field=models.ManyToManyField(blank=True, to='gestion.idioma'),
        ),
        migrations.AlterField(
            model_name='importador',
            name='paises_comercializa',
            field=models.ManyToManyField(blank=True, related_name='importadores_que_comercializan', to='gestion.pais'),
        ),
        migrations.AlterField(
            model_name='importador',
            name='rubros',
            field=models.ManyToManyField(blank=True, to='gestion.rubro'),
        ),
        migrations.AlterField(
            model_name='importador',
            name='tipos_proveedor',
            field=models.ManyToManyField(blank=True, to='gestion.tipoproveedor'),
        ),
    ]
