# Generated by Django 5.2.3 on 2025-09-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_alter_importador_idiomas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importador',
            name='cargo',
            field=models.CharField(choices=[('dueno_fundador', 'Dueño / Fundador'), ('gerente_general', 'Gerente General'), ('director_compras', 'Director de Compras'), ('resp_importaciones', 'Responsable de Importaciones'), ('jefe_logistica', 'Jefe de Logística'), ('asistente_comercial', 'Asistente Comercial'), ('encargado_proveedores', 'Encargado de Proveedores'), ('otro', 'Otro')], max_length=100),
        ),
    ]
