# Generated by Django 5.2.3 on 2025-09-10 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_alter_importador_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='importador', to=settings.AUTH_USER_MODEL),
        ),
    ]
